// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwUN22lU47dvD2tNP3Z9XlDN20acqhKFc',
    appId: '1:235247065863:web:f60da5542b8bcbfb1d83a2',
    messagingSenderId: '235247065863',
    projectId: 'my-provider-test',
    authDomain: 'my-provider-test.firebaseapp.com',
    storageBucket: 'my-provider-test.appspot.com',
    measurementId: 'G-LWLH3J703V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyfVJIQrg6nChNk59DtvAVJL79jbSHsjA',
    appId: '1:235247065863:android:1af208e3f15ef0ee1d83a2',
    messagingSenderId: '235247065863',
    projectId: 'my-provider-test',
    storageBucket: 'my-provider-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHqLyCZXyiDEeidfXUVtn6VpDtPs4fi74',
    appId: '1:235247065863:ios:c99c15afe29b23841d83a2',
    messagingSenderId: '235247065863',
    projectId: 'my-provider-test',
    storageBucket: 'my-provider-test.appspot.com',
    iosBundleId: 'com.example.myTestProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHqLyCZXyiDEeidfXUVtn6VpDtPs4fi74',
    appId: '1:235247065863:ios:80bccc7245b2ea301d83a2',
    messagingSenderId: '235247065863',
    projectId: 'my-provider-test',
    storageBucket: 'my-provider-test.appspot.com',
    iosBundleId: 'com.example.myTestProvider.RunnerTests',
  );
}
